# Generated by Django 5.0.4 on 2024-06-08 14:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('wedding_anniversary', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='follow_app.family')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=52)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=52)),
                ('phone_no', models.CharField(max_length=15)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('marital_status', models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Married')])),
                ('occupation', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=20)),
                ('kcc_center', models.CharField(max_length=20)),
                ('place_of_work', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=40)),
                ('wedding_ann', models.CharField()),
                ('join', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=20)),
                ('team_lead', models.CharField(blank=True, max_length=20, null=True)),
                ('team_member', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default='1')),
                ('kin_fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('kin_birth', models.DateField(blank=True, null=True)),
                ('kin_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('kin_relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('kin_address', models.CharField(blank=True, max_length=100, null=True)),
                ('kin_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('kin_email', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='husband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='follow_app.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='wife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='follow_app.member'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=25, null=True)),
                ('team_mem', models.CharField(blank=True, max_length=50, null=True)),
                ('coor_comm', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('comment', models.TextField()),
                ('team_sup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='follow_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Pastorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.team_lead')),
            ],
        ),
    ]
