# Generated by Django 5.0.4 on 2024-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wedding_ann',
            field=models.DateField(),
        ),
    ]
