# Generated by Django 5.0.4 on 2024-06-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='member',
        ),
        migrations.RemoveField(
            model_name='household',
            name='name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='position',
        ),
        migrations.AddField(
            model_name='household',
            name='household_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='members',
            field=models.ManyToManyField(through='follow_app.HouseholdMember', to='follow_app.member'),
        ),
    ]
