# Generated by Django 5.0.4 on 2024-06-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0002_alter_member_wedding_ann'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_address', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=15)),
                ('university_name', models.CharField(max_length=255)),
                ('program_of_study', models.CharField(max_length=255)),
                ('program', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('work_type', models.CharField(choices=[('Internship', 'Internship'), ('Part-time job', 'Part-time job')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='follow_app.member')),
            ],
        ),
    ]
