# Generated by Django 5.0.4 on 2024-06-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0002_remove_household_member_remove_household_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teenager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_school_name', models.CharField(max_length=255)),
                ('current_class', models.CharField(max_length=100)),
                ('last_class_position', models.CharField(max_length=50)),
                ('favorite_subjects', models.TextField()),
                ('career_goals', models.TextField()),
                ('college_plans', models.TextField(blank=True, null=True)),
                ('other_future_aspirations', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teenagers', to='follow_app.member')),
            ],
        ),
    ]
