# Generated by Django 4.2.4 on 2023-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0002_alter_member_team_member_alter_team_lead_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team_mem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
