# Generated by Django 4.2.4 on 2023-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0003_comment_team_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
