# Generated by Django 5.0.4 on 2024-06-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0005_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('is_registered', models.BooleanField(default=False, verbose_name='Is business registered')),
                ('brief_description', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of business experience')),
                ('number_of_employees', models.PositiveIntegerField(default=1)),
                ('business_sector', models.CharField(choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Manufacturing', 'Manufacturing'), ('Real Estate', 'Real Estate'), ('Hospitality', 'Hospitality'), ('Retail', 'Retail'), ('Entertainment', 'Entertainment')], max_length=100)),
                ('current_employment_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employment_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employment_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employment_responsibilities', models.TextField(blank=True, null=True)),
                ('previous_employment_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_employment_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_employment_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_employment_responsibilities', models.TextField(blank=True, null=True)),
                ('highest_qualification_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_qualification_year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('highest_qualification_gpa', models.FloatField(blank=True, null=True)),
                ('other_qualification_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('other_qualification_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('other_qualification_year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
                ('other_qualification_gpa', models.FloatField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('achievements_and_awards', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.member')),
            ],
        ),
    ]
