# Generated by Django 4.2.4 on 2023-09-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0005_comment_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='kcc_center',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
