# Generated by Django 5.0.4 on 2024-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0006_kbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbn',
            name='designation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
