# Generated by Django 4.2.4 on 2023-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0007_alter_member_address_alter_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
