# Generated by Django 5.0.4 on 2024-06-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0008_business_career_educationalbackground_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='responsibilities',
            new_name='achievements_and_awards',
        ),
        migrations.RemoveField(
            model_name='career',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='career',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='career',
            name='job_title',
        ),
        migrations.AddField(
            model_name='career',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CurrentEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_employments', to='follow_app.career')),
            ],
        ),
    ]
