# Generated by Django 5.0.4 on 2024-06-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0009_rename_responsibilities_career_achievements_and_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.PositiveIntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Teenager'), (4, 'Children')]),
        ),
    ]
