# Generated by Django 5.0.4 on 2024-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0010_alter_member_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='join',
            field=models.DateField(),
        ),
    ]
