# Generated by Django 5.0.4 on 2024-06-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0011_alter_member_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wedding_ann',
            field=models.DateField(blank=True, null=True),
        ),
    ]
