# Generated by Django 5.0.4 on 2024-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0013_alter_member_about_alter_member_dept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='wedding_anniversary',
        ),
        migrations.AddField(
            model_name='family',
            name='team_lead',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='team_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
